

# steps:
#   # Step 1: Install dependencies
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['install']
#     dir: 'ejs-app'  # Ensure npm is run in the ejs-app directory

#   # Step 2: Deploy to Google App Engine
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     args: ['gcloud', 'app', 'deploy', 'ejs-app/app.yaml']
#     dir: '.'  # Run the deployment from the root directory

# options:
#   logging: CLOUD_LOGGING_ONLY  # Ensures logs are sent to Cloud Logging

steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'AppEngineNoEnv'
    
  # Step 2: Deploy to Google App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy ejs-app/app.yaml --quiet']
    
options:
  logging: CLOUD_LOGGING_ONLY